# Generated by Django 5.2.8 on 2026-01-08 04:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('RESELLER', 'Reseller'), ('STAFF', 'Admin staff')], help_text='High-level role used for permissions and routing.', max_length=8, verbose_name='Role')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the email address has been verified.', verbose_name='Email Verified')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Timestamp when email was verified.', null=True, verbose_name='Email Verified At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User List',
                'ordering': ['-is_active', 'email'],
            },
        ),
        migrations.CreateModel(
            name='ResellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the reseller.', max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True, help_text='Business address.')),
                ('referral_code', models.CharField(db_index=True, help_text='Code this reseller can share so new members join under them in the same group / team.', max_length=20, unique=True)),
                ('base_commission', models.PositiveIntegerField(default=0, help_text='Base commission amount (fixed value) for each sale made directly by this reseller.', validators=[django.core.validators.MinValueValidator(0)])),
                ('upline_commission_amount', models.PositiveIntegerField(default=0, help_text='Fixed commission amount this reseller earns for each sale made by their direct downlines.', validators=[django.core.validators.MinValueValidator(0)])),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for commission payouts.', max_length=255, verbose_name='Bank Name')),
                ('bank_account_name', models.CharField(blank=True, help_text='Account holder name for commission payouts.', max_length=255, verbose_name='Bank Account Name')),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number for commission payouts.', max_length=100, verbose_name='Bank Account Number')),
                ('photo', models.ImageField(blank=True, help_text='Reseller profile photo.', null=True, upload_to='profile_photos/resellers/', verbose_name='Profile Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_root', models.ForeignKey(blank=True, editable=False, help_text="Top-most leader in this reseller's tree. Set automatically.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_members', to='account.resellerprofile')),
                ('sponsor', models.ForeignKey(blank=True, help_text='Direct upline / leader who invited this reseller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_downlines', to='account.resellerprofile')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'RESELLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='reseller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseller Profile',
                'verbose_name_plural': 'Reseller Profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the staff member.', max_length=255)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=50)),
                ('photo', models.ImageField(blank=True, help_text='Staff profile photo.', null=True, upload_to='profile_photos/staff/', verbose_name='Profile Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Official company/business name.', max_length=255)),
                ('contact_person', models.CharField(help_text='Primary contact person name.', max_length=255)),
                ('contact_phone', models.CharField(help_text='Primary contact phone number.', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Business address.')),
                ('photo', models.ImageField(blank=True, help_text='Supplier profile photo.', null=True, upload_to='profile_photos/suppliers/', verbose_name='Profile Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Profile',
                'verbose_name_plural': 'Supplier Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='account_cus_email_5f481e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='account_cus_role_8abfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email_verified'], name='account_cus_email_v_66732f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'role', 'email_verified'], name='account_cus_is_acti_d4e16d_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['full_name'], name='account_res_full_na_f19f90_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['referral_code'], name='account_res_referra_561096_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['user'], name='account_res_user_id_dc9c79_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['sponsor'], name='account_res_sponsor_8586bd_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['group_root'], name='account_res_group_r_923821_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['created_at'], name='account_res_created_087bee_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['user', 'created_at'], name='account_res_user_id_084eae_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['sponsor', 'created_at'], name='account_res_sponsor_bbc71e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['user'], name='account_sta_user_id_b1d166_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['created_at'], name='account_sta_created_959afd_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['user', 'created_at'], name='account_sta_user_id_fd386f_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['company_name'], name='account_sup_company_73b8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['user'], name='account_sup_user_id_c56b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['created_at'], name='account_sup_created_c09df7_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['user', 'created_at'], name='account_sup_user_id_8fe08d_idx'),
        ),
    ]
