# Generated by Django 5.2.8 on 2025-12-02 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('RESELLER', 'Reseller'), ('STAFF', 'Admin staff'), ('CUSTOMER', 'Customer')], default='RESELLER', help_text='High-level role used for permissions and routing.', max_length=20, verbose_name='Role')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, verbose_name='Phone Number')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the email address has been verified.', verbose_name='Email Verified')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Timestamp when email was verified.', null=True, verbose_name='Email Verified At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User List',
                'ordering': ['-is_active', 'email'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's first name.", max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Customer's last name.", max_length=255, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact phone number.', max_length=50, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, help_text='Street address.', verbose_name='Address')),
                ('city', models.CharField(blank=True, help_text='City name.', max_length=100, verbose_name='City')),
                ('country', models.CharField(blank=True, help_text='Country name.', max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code.', max_length=20, verbose_name='Postal Code')),
                ('date_of_birth', models.DateField(blank=True, help_text="Customer's date of birth.", null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text='Gender identity.', max_length=10, verbose_name='Gender')),
                ('preferred_language', models.CharField(default='en', help_text="Preferred language code (e.g., 'en', 'id').", max_length=10, verbose_name='Preferred Language')),
                ('preferred_currency', models.CharField(default='IDR', help_text="Preferred currency code (e.g., 'IDR', 'USD').", max_length=10, verbose_name='Preferred Currency')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Name of emergency contact person.', max_length=255, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Phone number of emergency contact.', max_length=50, verbose_name='Emergency Contact Phone')),
                ('travel_interests', models.JSONField(blank=True, default=list, help_text="List of travel interests/preferences (e.g., ['beach', 'adventure']).", verbose_name='Travel Interests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='ResellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Public / brand name shown to customers.', max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True, help_text='Business address.')),
                ('referral_code', models.CharField(db_index=True, help_text='Code this reseller can share so new members join under them in the same group / team.', max_length=20, unique=True)),
                ('own_commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Default percentage this reseller earns from the commissionable amount of their own bookings.', max_digits=5)),
                ('upline_commission_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Suggested percentage for direct upline override commissions, if your business logic uses it.', max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', help_text='Reseller account status (pending verification, active, or suspended).', max_length=20, verbose_name='Status')),
                ('bank_name', models.CharField(blank=True, help_text='Bank name for commission payouts.', max_length=255, verbose_name='Bank Name')),
                ('bank_account_name', models.CharField(blank=True, help_text='Account holder name for commission payouts.', max_length=255, verbose_name='Bank Account Name')),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number for commission payouts.', max_length=100, verbose_name='Bank Account Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_root', models.ForeignKey(blank=True, editable=False, help_text="Top-most leader in this reseller's tree. Set automatically.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_members', to='account.resellerprofile')),
                ('sponsor', models.ForeignKey(blank=True, help_text='Direct upline / leader who invited this reseller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_downlines', to='account.resellerprofile')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'RESELLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='reseller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseller Profile',
                'verbose_name_plural': 'Reseller Profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the staff member.', max_length=255)),
                ('job_title', models.CharField(blank=True, help_text='Job title or position.', max_length=255)),
                ('department', models.CharField(blank=True, help_text='Department or division.', max_length=255)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Official company/business name.', max_length=255)),
                ('contact_person', models.CharField(help_text='Primary contact person name.', max_length=255)),
                ('contact_phone', models.CharField(help_text='Primary contact phone number.', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Business address.')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number.', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', help_text='Supplier account status (pending verification, active, or suspended).', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Profile',
                'verbose_name_plural': 'Supplier Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='account_cus_email_5f481e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='account_cus_role_8abfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['first_name', 'last_name'], name='account_cus_first_n_5d895c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['phone_number'], name='account_cus_phone_n_30f206_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['display_name'], name='account_res_display_133af3_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['status'], name='account_res_status_7a8516_idx'),
        ),
        migrations.AddIndex(
            model_name='resellerprofile',
            index=models.Index(fields=['referral_code'], name='account_res_referra_561096_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['company_name'], name='account_sup_company_73b8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['status'], name='account_sup_status_afbcbc_idx'),
        ),
    ]
