# Generated by Django 5.2.8 on 2026-01-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('RESELLER', 'Reseller'), ('STAFF', 'Admin staff')], help_text='High-level role used for permissions and routing.', max_length=8, verbose_name='Role'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='account_cus_email_4c4c85_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='account_cus_role_d1c4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email_verified'], name='account_cus_email_v_89e5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'role', 'email_verified'], name='account_cus_is_acti_f5b6d1_idx'),
        ),
    ]

