# Generated by Django 5.2.8 on 2026-01-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resellerprofile',
            name='upline_commission_amount',
        ),
    ]
