# Generated by Django 5.2.8 on 2025-11-28 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
        migrations.CreateModel(
            name='ResellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Public / brand name shown to customers.', max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('referral_code', models.CharField(db_index=True, help_text='Code this reseller can share so new members join under them in the same group / team.', max_length=20, unique=True)),
                ('own_commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Default percentage this reseller earns from the commissionable amount of their own bookings.', max_digits=5)),
                ('upline_commission_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Suggested percentage for direct upline override commissions, if your business logic uses it.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_root', models.ForeignKey(blank=True, editable=False, help_text="Top-most leader in this reseller's tree. Set automatically.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_members', to='account.resellerprofile')),
                ('sponsor', models.ForeignKey(blank=True, help_text='Direct upline / leader who invited this reseller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_downlines', to='account.resellerprofile')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'RESELLER'}, on_delete=django.db.models.deletion.CASCADE, related_name='reseller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseller Profile',
                'verbose_name_plural': 'Reseller Profiles',
                'indexes': [models.Index(fields=['display_name'], name='account_res_display_133af3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'SUPPLIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Profile',
                'verbose_name_plural': 'Supplier Profiles',
                'indexes': [models.Index(fields=['company_name'], name='account_sup_company_73b8c6_idx')],
            },
        ),
    ]
