# Generated by Django 5.2.8 on 2026-01-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_role_and_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='account_cus_email_4c4c85_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='account_cus_role_d1c4f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='account_cus_email_v_89e5e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='account_cus_is_acti_f5b6d1_idx',
        ),
    ]
