# Generated by Django 5.2.8 on 2026-01-16 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_resellerprofile_upline_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('RESELLER', 'Reseller'), ('STAFF', 'Admin staff'), ('CUSTOMER', 'Customer')], help_text='High-level role used for permissions and routing.', max_length=8, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the customer.', max_length=255)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Customer address for billing/shipping purposes.')),
                ('photo', models.ImageField(blank=True, help_text='Customer profile photo.', null=True, upload_to='profile_photos/customers/', verbose_name='Profile Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'indexes': [models.Index(fields=['user'], name='account_cus_user_id_44895f_idx'), models.Index(fields=['full_name'], name='account_cus_full_na_e3427f_idx'), models.Index(fields=['created_at'], name='account_cus_created_d6dac4_idx'), models.Index(fields=['user', 'created_at'], name='account_cus_user_id_1fad32_idx')],
            },
        ),
    ]
