# Generated by Django 5.2.8 on 2026-01-09 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_allow_dual_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Approval status for supplier account. Suppliers need admin approval to access dashboard.', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the supplier was approved.', null=True),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved this supplier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected).'),
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['approval_status'], name='account_sup_approva_cf78cb_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprofile',
            index=models.Index(fields=['approval_status', 'created_at'], name='account_sup_approva_63702e_idx'),
        ),
    ]
