# Generated by Django 5.2.8 on 2026-01-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_role_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account holder name for commission payouts.', max_length=255, verbose_name='Bank Account Name'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number for commission payouts.', max_length=100, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for commission payouts.', max_length=255, verbose_name='Bank Name'),
        ),
    ]
