# Generated by Django 5.2.8 on 2026-01-07 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_account_cus_email_4c4c85_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resellerprofile',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='resellerprofile',
            name='upline_commission_rate',
        ),
        migrations.AddField(
            model_name='resellerprofile',
            name='base_commission',
            field=models.PositiveIntegerField(default=0, help_text='Base commission amount (fixed value) for each sale made directly by this reseller.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='resellerprofile',
            name='upline_commission_amount',
            field=models.PositiveIntegerField(default=0, help_text='Fixed commission amount this reseller earns for each sale made by their direct downlines.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
