# Generated by Django 5.2.8 on 2026-01-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_supplierprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting the contact form.', max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Email address of the person submitting the form.', max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Optional phone number for callback.', max_length=20, null=True, verbose_name='Phone Number')),
                ('subject', models.CharField(choices=[('general', 'Pertanyaan Umum'), ('supplier', 'Dukungan Supplier'), ('reseller', 'Dukungan Reseller'), ('billing', 'Pertanyaan Tagihan'), ('other', 'Lainnya')], help_text='Category of the inquiry.', max_length=20, verbose_name='Subject')),
                ('message', models.TextField(help_text='Detailed message from the user.', verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='account_con_created_5f23e1_idx'), models.Index(fields=['email'], name='account_con_email_992d6f_idx'), models.Index(fields=['subject'], name='account_con_subject_37977c_idx')],
            },
        ),
    ]
