# Generated by Django 5.2.8 on 2026-01-08 03:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(help_text='Departure date for this tour. Must be in the future.')),
                ('price', models.PositiveIntegerField(help_text='Price per person in IDR (Indonesian Rupiah) for this tour date. Must be greater than zero.', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_seats', models.PositiveIntegerField(help_text='Total number of seats available. Must be at least 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_high_season', models.BooleanField(default=False, help_text='Mark if this date is considered high season.')),
            ],
            options={
                'verbose_name': 'Tour Date',
                'verbose_name_plural': 'Tour Dates',
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Primary booking contact name (person making the booking). This may or may not be the same as the passengers. For group bookings, this is typically the group organizer or travel agent contact.', max_length=255)),
                ('customer_email', models.EmailField(help_text='Email of the booking contact (for booking confirmations and communication).', max_length=254)),
                ('customer_phone', models.CharField(blank=True, help_text='Phone number of the booking contact.', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('platform_fee', models.PositiveIntegerField(default=50000, help_text='Platform fee in IDR (default: Rp. 50,000).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.resellerprofile')),
                ('tour_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='travel.tourdate')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the reseller group (must be unique).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the group and its purpose.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this group (supplier or admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reseller_groups', to=settings.AUTH_USER_MODEL)),
                ('resellers', models.ManyToManyField(blank=True, help_text='Resellers belonging to this group.', related_name='reseller_groups', to='account.resellerprofile')),
            ],
            options={
                'verbose_name': 'Reseller Group',
                'verbose_name_plural': 'Reseller Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeatSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text="Seat identifier (e.g., 'A1', 'B12', or sequential number).", max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('passenger_name', models.CharField(blank=True, help_text='Full name of the passenger.', max_length=255)),
                ('passenger_email', models.EmailField(blank=True, max_length=254)),
                ('passenger_phone', models.CharField(blank=True, max_length=50)),
                ('passenger_date_of_birth', models.DateField(blank=True, help_text='Passenger date of birth.', null=True)),
                ('passenger_gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('passenger_nationality', models.CharField(blank=True, help_text='Passenger nationality (country code or name).', max_length=100)),
                ('passport_number', models.CharField(blank=True, help_text='Passport number.', max_length=50)),
                ('passport_issue_date', models.DateField(blank=True, help_text='Passport issue date.', null=True)),
                ('passport_expiry_date', models.DateField(blank=True, help_text='Passport expiry date.', null=True)),
                ('passport_issue_country', models.CharField(blank=True, help_text='Country that issued the passport.', max_length=100)),
                ('visa_required', models.BooleanField(default=False, help_text='Whether visa is required for this passenger.')),
                ('visa_number', models.CharField(blank=True, help_text='Visa number if applicable.', max_length=50)),
                ('visa_issue_date', models.DateField(blank=True, help_text='Visa issue date.', null=True)),
                ('visa_expiry_date', models.DateField(blank=True, help_text='Visa expiry date.', null=True)),
                ('visa_type', models.CharField(blank=True, help_text="Type of visa (e.g., 'Tourist', 'Business', 'Transit').", max_length=50)),
                ('special_requests', models.TextField(blank=True, help_text='Special requests or dietary restrictions.')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact name.', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Booking this seat belongs to (null if available).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_slots', to='travel.booking')),
                ('tour_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_slots', to='travel.tourdate')),
            ],
            options={
                'verbose_name': 'Seat Slot',
                'verbose_name_plural': 'Seat Slots',
                'ordering': ['tour_date', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(help_text='Summary of the tour package.')),
                ('description', models.TextField(help_text='Detailed description of the tour package.')),
                ('itinerary', models.TextField(help_text='Day-by-day itinerary of the tour package.')),
                ('country', models.CharField(help_text="Country where the tour takes place (e.g., 'China', 'Japan').", max_length=255)),
                ('days', models.PositiveIntegerField(help_text='Number of days for the tour.')),
                ('nights', models.PositiveIntegerField(help_text='Number of nights for the tour.')),
                ('max_group_size', models.PositiveIntegerField(default=12, help_text='Maximum number of participants in a group.')),
                ('group_type', models.CharField(choices=[('SMALL_GROUP', 'Small Group'), ('PRIVATE', 'Private'), ('LARGE_GROUP', 'Large Group'), ('FAMILY', 'Family'), ('COUPLE', 'Couple'), ('SOLO', 'Solo')], default='SMALL_GROUP', help_text='Type of group for this tour package.', max_length=20)),
                ('tour_type', models.CharField(choices=[('CONVENTIONAL', 'Conventional Tour'), ('MUSLIM', 'Muslim Tour')], default='CONVENTIONAL', help_text='Tour type: Conventional Tour or Muslim Tour (for Indonesian citizens).', max_length=20)),
                ('category', models.CharField(choices=[('ADVENTURE', 'Adventure'), ('CULTURAL', 'Cultural'), ('BEACH', 'Beach'), ('CITY_BREAK', 'City Break'), ('NATURE', 'Nature'), ('FAMILY', 'Family')], help_text='Primary category for the tour.', max_length=50)),
                ('highlights', models.JSONField(default=list, help_text="List of key highlights/attractions (e.g., ['Forbidden City', 'Great Wall']).")),
                ('inclusions', models.JSONField(blank=True, default=list, help_text="List of what's included (e.g., ['Hotel accommodation', 'Breakfast', 'Transportation']).")),
                ('exclusions', models.JSONField(blank=True, default=list, help_text="List of what's not included (e.g., ['International flights', 'Travel insurance']).")),
                ('meeting_point', models.CharField(blank=True, help_text='Where participants should meet for the tour.', max_length=500)),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation and refund policy details.')),
                ('important_notes', models.TextField(blank=True, help_text='Important information participants should know.')),
                ('base_price', models.PositiveIntegerField(help_text='Reference price in IDR (Indonesian Rupiah). Must be at least 1 IDR. Actual price can vary per date.', validators=[django.core.validators.MinValueValidator(1)])),
                ('badge', models.CharField(blank=True, choices=[('BEST_SELLER', 'Best Seller'), ('POPULAR', 'Popular'), ('TOP_RATED', 'Top Rated'), ('NEW', 'New')], help_text="Featured badge (e.g., 'BEST_SELLER', 'POPULAR').", max_length=20, null=True)),
                ('main_image', models.ImageField(blank=True, help_text='Main featured image for the tour.', null=True, upload_to='tours/main/')),
                ('itinerary_pdf', models.FileField(blank=True, help_text='PDF file containing the detailed itinerary for the tour package.', null=True, upload_to='tours/itineraries/')),
                ('commission', models.PositiveIntegerField(blank=True, help_text='Commission amount for the tour package.', null=True)),
                ('commission_notes', models.TextField(blank=True, help_text='Admin notes about commission settings for this tour.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this tour on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller_groups', models.ManyToManyField(blank=True, help_text='Reseller groups that can access this tour package. If empty, tour is visible to all resellers. If not empty, only resellers in these groups can see this tour.', related_name='tour_packages', to='travel.resellergroup')),
                ('supplier', models.ForeignKey(help_text='Supplier who created and owns this tour package.', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='account.supplierprofile')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Tour gallery image.', upload_to='tours/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is a primary image (shown first). Only one primary image allowed per package.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.tourpackage')),
            ],
            options={
                'verbose_name': 'Tour Image',
                'verbose_name_plural': 'Tour Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tourdate',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='travel.tourpackage'),
        ),
        migrations.CreateModel(
            name='ResellerTourCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.PositiveIntegerField(help_text='Fixed commission amount in IDR for this reseller for this tour package. Must be greater than zero.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this commission setting is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(help_text='Reseller who will receive this commission.', on_delete=django.db.models.deletion.CASCADE, related_name='tour_commissions', to='account.resellerprofile')),
                ('tour_package', models.ForeignKey(help_text='Tour package this commission applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='reseller_commissions', to='travel.tourpackage')),
            ],
            options={
                'verbose_name': 'Reseller Tour Commission',
                'verbose_name_plural': 'Reseller Tour Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Payment amount in IDR (Indonesian Rupiah). Must be greater than zero.', validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('transfer_date', models.DateField(help_text='Date when the transfer was made. Cannot be in the future.')),
                ('sender_account_name', models.CharField(max_length=255)),
                ('sender_bank_name', models.CharField(max_length=255)),
                ('sender_account_number', models.CharField(max_length=64)),
                ('proof_image', models.ImageField(blank=True, help_text='Upload of the bank transfer slip or screenshot.', null=True, upload_to='payments/proof/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='travel.booking')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='travel_paym_status_63ceb2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='0 = booking owner, 1 = direct upline, 2+ = higher levels.')),
                ('amount', models.PositiveIntegerField(help_text='Commission amount in IDR (Indonesian Rupiah). Must be at least 1 IDR.', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='travel.booking')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='account.resellerprofile')),
            ],
            options={
                'verbose_name': 'Reseller Commission',
                'verbose_name_plural': 'Reseller Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reseller', 'level'], name='travel_rese_reselle_328f39_idx'), models.Index(fields=['booking', 'reseller'], name='travel_rese_booking_e53501_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resellergroup',
            index=models.Index(fields=['is_active'], name='travel_rese_is_acti_d0fbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='resellergroup',
            index=models.Index(fields=['name'], name='travel_rese_name_8fa735_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['tour_date', 'status'], name='travel_seat_tour_da_f2cf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['booking'], name='travel_seat_booking_773e95_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['booking', 'status'], name='travel_seat_booking_1439c0_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['status'], name='travel_seat_status_c465c5_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['passenger_email'], name='travel_seat_passeng_e4ab98_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['passport_number'], name='travel_seat_passpor_f55464_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seatslot',
            unique_together={('tour_date', 'seat_number')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reseller', 'status'], name='travel_book_reselle_cec691_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tour_date', 'status'], name='travel_book_tour_da_dbe48b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='travel_book_status_0d8923_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='travel_book_created_5dc42a_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['category', 'is_active'], name='travel_tour_categor_8f18b4_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['is_featured'], name='travel_tour_is_feat_762625_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['tour_type', 'is_active'], name='travel_tour_tour_ty_2925a0_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['supplier', 'is_active'], name='travel_tour_supplie_73caaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.CheckConstraint(condition=models.Q(('nights__lte', models.F('days'))), name='nights_not_greater_than_days'),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.CheckConstraint(condition=models.Q(('commission__isnull', True), ('commission__gte', 1), _connector='OR'), name='commission_valid'),
        ),
        migrations.AddIndex(
            model_name='tourimage',
            index=models.Index(fields=['package', 'is_primary'], name='travel_tour_package_d33d51_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['package', 'departure_date'], name='travel_tour_package_65cac6_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['departure_date', 'is_high_season'], name='travel_tour_departu_67d759_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['package', 'is_high_season'], name='travel_tour_package_4d7eae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together={('package', 'departure_date')},
        ),
        migrations.AddIndex(
            model_name='resellertourcommission',
            index=models.Index(fields=['reseller', 'is_active'], name='travel_rese_reselle_49c90e_idx'),
        ),
        migrations.AddIndex(
            model_name='resellertourcommission',
            index=models.Index(fields=['tour_package', 'is_active'], name='travel_rese_tour_pa_335dbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resellertourcommission',
            unique_together={('reseller', 'tour_package')},
        ),
    ]
