# Generated by Django 5.2.8 on 2025-11-28 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_staffprofile_resellerprofile_supplierprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_seats', models.PositiveIntegerField()),
                ('remaining_seats', models.PositiveIntegerField()),
                ('is_high_season', models.BooleanField(default=False, help_text='Mark if this date is considered high season.')),
            ],
            options={
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('seats_booked', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.resellerprofile')),
                ('tour_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='travel.tourdate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('transfer_date', models.DateField()),
                ('sender_account_name', models.CharField(max_length=255)),
                ('sender_bank_name', models.CharField(max_length=255)),
                ('sender_account_number', models.CharField(max_length=64)),
                ('proof_image', models.ImageField(blank=True, help_text='Upload of the bank transfer slip or screenshot.', null=True, upload_to='payments/proof/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='travel.booking')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Reference price; actual price can vary per date.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='account.supplierprofile')),
            ],
        ),
        migrations.AddField(
            model_name='tourdate',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='travel.tourpackage'),
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='travel.tourpackage')),
            ],
            options={
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='0 = booking owner, 1 = direct upline, 2+ = higher levels.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='travel.booking')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='account.resellerprofile')),
            ],
            options={
                'verbose_name': 'Reseller Commission',
                'verbose_name_plural': 'Reseller Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reseller', 'level'], name='travel_rese_reselle_328f39_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together={('package', 'departure_date')},
        ),
    ]
