# Generated by Django 5.2.8 on 2026-01-10 03:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(help_text='Departure date for this tour. Must be in the future.')),
                ('price', models.IntegerField(default=0, help_text='Price per person in IDR (Indonesian Rupiah) for this tour date.', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_seats', models.PositiveIntegerField(help_text='Total number of seats available. Must be at least 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('airline', models.CharField(blank=True, help_text='Airline for this tour date.', max_length=255, null=True)),
                ('is_high_season', models.BooleanField(default=False, help_text='Mark if this date is considered high season.')),
            ],
            options={
                'verbose_name': 'Tour Date',
                'verbose_name_plural': 'Tour Dates',
                'ordering': ['departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('platform_fee', models.IntegerField(default=50000, help_text='Platform fee in IDR (default: Rp. 50,000).', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.IntegerField(default=0, help_text='Total booking amount in IDR (Indonesian Rupiah).', validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('booking_number', models.CharField(db_index=True, help_text='Unique professional booking reference number (e.g., BK-2024-000123).', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.resellerprofile')),
                ('tour_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='travel.tourdate')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the reseller group (must be unique).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the group and its purpose.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this group (supplier or admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reseller_groups', to=settings.AUTH_USER_MODEL)),
                ('resellers', models.ManyToManyField(blank=True, help_text='Resellers belonging to this group.', related_name='reseller_groups', to='account.resellerprofile')),
            ],
            options={
                'verbose_name': 'Reseller Group',
                'verbose_name_plural': 'Reseller Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeatSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(db_index=True, help_text="Seat identifier (e.g., 'A1', 'B12', or sequential number).", max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('passenger_name', models.CharField(blank=True, help_text='Full name of the passenger.', max_length=255)),
                ('passport', models.ImageField(blank=True, help_text='Passport image.', null=True, upload_to='passports/')),
                ('visa_required', models.BooleanField(default=False, help_text='Whether visa is required for this passenger.')),
                ('special_requests', models.TextField(blank=True, help_text='Special requests or dietary restrictions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Booking this seat belongs to (null if available).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_slots', to='travel.booking')),
                ('tour_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_slots', to='travel.tourdate')),
            ],
            options={
                'verbose_name': 'Seat Slot',
                'verbose_name_plural': 'Seat Slots',
                'ordering': ['tour_date', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('itinerary', models.TextField(help_text='Day-by-day itinerary of the tour package.')),
                ('country', models.CharField(help_text="Country where the tour takes place (e.g., 'China', 'Japan').", max_length=255)),
                ('days', models.PositiveIntegerField(help_text='Number of days for the tour.')),
                ('nights', models.PositiveIntegerField(help_text='Number of nights for the tour.')),
                ('max_group_size', models.PositiveIntegerField(default=12, help_text='Maximum number of participants in a group.')),
                ('tour_type', models.CharField(choices=[('CONVENTIONAL', 'Conventional Tour'), ('MUSLIM', 'Muslim Tour')], default='CONVENTIONAL', help_text='Tour type: Conventional Tour or Muslim Tour (for Indonesian citizens).', max_length=20)),
                ('highlights', models.JSONField(default=list, help_text="List of key highlights/attractions (e.g., ['Forbidden City', 'Great Wall']).")),
                ('inclusions', models.JSONField(blank=True, default=list, help_text="List of what's included (e.g., ['Hotel accommodation', 'Breakfast', 'Transportation']).")),
                ('exclusions', models.JSONField(blank=True, default=list, help_text="List of what's not included (e.g., ['International flights', 'Travel insurance']).")),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation and refund policy details.')),
                ('important_notes', models.TextField(blank=True, help_text='Important information participants should know.')),
                ('base_price', models.IntegerField(default=0, help_text='Reference price in IDR (Indonesian Rupiah). Actual price can vary per date.', validators=[django.core.validators.MinValueValidator(0)])),
                ('visa_price', models.IntegerField(default=0, help_text='Visa price in IDR (Indonesian Rupiah). Actual price can vary per date.', validators=[django.core.validators.MinValueValidator(0)])),
                ('tipping_price', models.IntegerField(default=0, help_text='Tipping price in IDR (Indonesian Rupiah). Actual price can vary per date.', validators=[django.core.validators.MinValueValidator(0)])),
                ('itinerary_pdf', models.FileField(blank=True, help_text='PDF file containing the detailed itinerary for the tour package.', null=True, upload_to='tours/itineraries/')),
                ('commission', models.IntegerField(default=0, help_text='Commission amount per seat (per passenger) in IDR for the tour package.', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller_groups', models.ManyToManyField(blank=True, help_text='Reseller groups that can access this tour package. If empty, tour is visible to all resellers. If not empty, only resellers in these groups can see this tour.', related_name='tour_packages', to='travel.resellergroup')),
                ('supplier', models.ForeignKey(help_text='Supplier who created and owns this tour package.', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='account.supplierprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Tour gallery image.', upload_to='tours/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is a primary image (shown first). Only one primary image allowed per package.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.tourpackage')),
            ],
            options={
                'verbose_name': 'Tour Image',
                'verbose_name_plural': 'Tour Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tourdate',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='travel.tourpackage'),
        ),
        migrations.CreateModel(
            name='ResellerTourCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.PositiveIntegerField(help_text='Fixed commission amount per seat (per passenger) in IDR for this reseller for this tour package. Must be greater than zero.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this commission setting is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reseller', models.ForeignKey(help_text='Reseller who will receive this commission.', on_delete=django.db.models.deletion.CASCADE, related_name='tour_commissions', to='account.resellerprofile')),
                ('tour_package', models.ForeignKey(help_text='Tour package this commission applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='reseller_commissions', to='travel.tourpackage')),
            ],
            options={
                'verbose_name': 'Reseller Tour Commission',
                'verbose_name_plural': 'Reseller Tour Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Withdrawal amount in IDR (Indonesian Rupiah). Must be at least 1 IDR.', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current status of the withdrawal request.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from reseller or admin.')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes (e.g., reason for rejection, payment confirmation).')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the withdrawal was approved/rejected.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the withdrawal payment was completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin user who approved/rejected this withdrawal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(help_text='Reseller requesting the withdrawal.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='account.resellerprofile')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='Payment amount in IDR (Indonesian Rupiah).', validators=[django.core.validators.MinValueValidator(0)])),
                ('transfer_date', models.DateField(help_text='Date when the transfer was made. Cannot be in the future.')),
                ('proof_image', models.ImageField(blank=True, help_text='Upload of the bank transfer slip or screenshot.', null=True, upload_to='payments/proof/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='travel.booking')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='travel_paym_status_63ceb2_idx'), models.Index(fields=['booking'], name='travel_paym_booking_200cd4_idx'), models.Index(fields=['reviewed_by'], name='travel_paym_reviewe_6ed600_idx'), models.Index(fields=['transfer_date'], name='travel_paym_transfe_d5b155_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='ResellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='0 = booking owner, 1 = direct upline, 2+ = higher levels.')),
                ('amount', models.PositiveIntegerField(help_text='Total commission amount in IDR (commission_per_seat × number_of_seats). Must be at least 1 IDR.', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='travel.booking')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='account.resellerprofile')),
            ],
            options={
                'verbose_name': 'Reseller Commission',
                'verbose_name_plural': 'Reseller Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reseller', 'level'], name='travel_rese_reselle_328f39_idx'), models.Index(fields=['booking', 'reseller'], name='travel_rese_booking_e53501_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resellergroup',
            index=models.Index(fields=['is_active'], name='travel_rese_is_acti_d0fbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='resellergroup',
            index=models.Index(fields=['name'], name='travel_rese_name_8fa735_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['tour_date', 'status'], name='travel_seat_tour_da_f2cf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['booking'], name='travel_seat_booking_773e95_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['booking', 'status'], name='travel_seat_booking_1439c0_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['status'], name='travel_seat_status_c465c5_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['tour_date', 'booking'], name='travel_seat_tour_da_984fe7_idx'),
        ),
        migrations.AddConstraint(
            model_name='seatslot',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number', ''), _negated=True), name='seat_number_not_empty'),
        ),
        migrations.AlterUniqueTogether(
            name='seatslot',
            unique_together={('tour_date', 'seat_number')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reseller', 'status'], name='travel_book_reselle_cec691_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tour_date', 'status'], name='travel_book_tour_da_dbe48b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='travel_book_status_0d8923_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='travel_book_created_5dc42a_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['tour_type', 'is_active'], name='travel_tour_tour_ty_2925a0_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['supplier', 'is_active'], name='travel_tour_supplie_73caaf_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['slug'], name='travel_tour_slug_f6819e_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['country'], name='travel_tour_country_4c974b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.CheckConstraint(condition=models.Q(('nights__lte', models.F('days'))), name='nights_not_greater_than_days'),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.CheckConstraint(condition=models.Q(('commission__gte', 0)), name='commission_valid'),
        ),
        migrations.AddIndex(
            model_name='tourimage',
            index=models.Index(fields=['package', 'is_primary'], name='travel_tour_package_d33d51_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['package', 'departure_date'], name='travel_tour_package_65cac6_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['departure_date', 'is_high_season'], name='travel_tour_departu_67d759_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['package', 'is_high_season'], name='travel_tour_package_4d7eae_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['departure_date'], name='travel_tour_departu_b9e232_idx'),
        ),
        migrations.AddConstraint(
            model_name='tourdate',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='tour_date_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tourdate',
            constraint=models.CheckConstraint(condition=models.Q(('total_seats__gte', 1)), name='tour_date_seats_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together={('package', 'departure_date')},
        ),
        migrations.AddIndex(
            model_name='resellertourcommission',
            index=models.Index(fields=['reseller', 'is_active'], name='travel_rese_reselle_49c90e_idx'),
        ),
        migrations.AddIndex(
            model_name='resellertourcommission',
            index=models.Index(fields=['tour_package', 'is_active'], name='travel_rese_tour_pa_335dbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resellertourcommission',
            unique_together={('reseller', 'tour_package')},
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['reseller', 'status'], name='travel_with_reselle_18d938_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'created_at'], name='travel_with_status_5ab75a_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['created_at'], name='travel_with_created_1af16e_idx'),
        ),
    ]
