# Generated by Django 5.2.8 on 2026-01-02 05:32

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='itineraryitem',
            options={'ordering': ['day_number', 'id'], 'verbose_name': 'Itinerary Item', 'verbose_name_plural': 'Itinerary Items'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='seatslot',
            options={'ordering': ['tour_date', 'seat_number'], 'verbose_name': 'Seat Slot', 'verbose_name_plural': 'Seat Slots'},
        ),
        migrations.AlterModelOptions(
            name='tourdate',
            options={'ordering': ['departure_date'], 'verbose_name': 'Tour Date', 'verbose_name_plural': 'Tour Dates'},
        ),
        migrations.AlterModelOptions(
            name='tourimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Tour Image', 'verbose_name_plural': 'Tour Images'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats_booked',
        ),
        migrations.RemoveField(
            model_name='tourdate',
            name='remaining_seats',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(help_text='Email of the booking contact (for booking confirmations and communication).', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(help_text='Primary booking contact name (person making the booking). This may or may not be the same as the passengers. For group bookings, this is typically the group organizer or travel agent contact.', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Phone number of the booking contact.', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='platform_fee',
            field=models.PositiveIntegerField(default=50000, help_text='Platform fee in IDR (default: Rp. 50,000).'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Payment amount in IDR (Indonesian Rupiah). Must be greater than zero.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transfer_date',
            field=models.DateField(help_text='Date when the transfer was made. Cannot be in the future.'),
        ),
        migrations.AlterField(
            model_name='resellercommission',
            name='amount',
            field=models.PositiveIntegerField(help_text='Commission amount in IDR (Indonesian Rupiah). Must be at least 1 IDR.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='resellergroup',
            name='name',
            field=models.CharField(help_text='Name of the reseller group (must be unique).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='resellertourcommission',
            name='commission_amount',
            field=models.PositiveIntegerField(help_text='Fixed commission amount in IDR for this reseller for this tour package. Must be greater than zero.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='departure_date',
            field=models.DateField(help_text='Departure date for this tour. Must be in the future.'),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='price',
            field=models.PositiveIntegerField(help_text='Price per person in IDR (Indonesian Rupiah) for this tour date. Must be greater than zero.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='total_seats',
            field=models.PositiveIntegerField(help_text='Total number of seats available. Must be at least 1.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Whether this is a primary image (shown first). Only one primary image allowed per package.'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='base_price',
            field=models.PositiveIntegerField(help_text='Reference price in IDR (Indonesian Rupiah). Must be at least 1 IDR. Actual price can vary per date.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='currency',
            field=models.CharField(default='IDR', help_text='Currency code. Defaults to IDR (Indonesian Rupiah).', max_length=10),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='fixed_commission_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Fixed commission amount in IDR (if commission_type is FIXED). Admin-only field.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryitem',
            unique_together={('package', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reseller', 'status'], name='travel_book_reselle_cec691_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tour_date', 'status'], name='travel_book_tour_da_dbe48b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='travel_book_status_0d8923_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='travel_book_created_5dc42a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='travel_paym_status_63ceb2_idx'),
        ),
        migrations.AddIndex(
            model_name='resellercommission',
            index=models.Index(fields=['booking', 'reseller'], name='travel_rese_booking_e53501_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['booking', 'status'], name='travel_seat_booking_1439c0_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['status'], name='travel_seat_status_c465c5_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['passenger_email'], name='travel_seat_passeng_e4ab98_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['passport_number'], name='travel_seat_passpor_f55464_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['package', 'departure_date'], name='travel_tour_package_65cac6_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['departure_date', 'is_high_season'], name='travel_tour_departu_67d759_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['package', 'is_high_season'], name='travel_tour_package_4d7eae_idx'),
        ),
        migrations.AddIndex(
            model_name='tourimage',
            index=models.Index(fields=['package', 'is_primary'], name='travel_tour_package_d33d51_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['supplier', 'is_active'], name='travel_tour_supplie_73caaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.CheckConstraint(condition=models.Q(('nights__lte', models.F('days'))), name='nights_not_greater_than_days'),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_commission_amount__isnull', True), models.Q(('commission_type', 'FIXED'), ('fixed_commission_amount__gte', 1)), _connector='OR'), name='fixed_commission_valid_when_fixed_type'),
        ),
    ]
