# Generated by Django 5.2.8 on 2025-12-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='tour_type',
            field=models.CharField(choices=[('CONVENTIONAL', 'Conventional Tour'), ('MUSLIM', 'Muslim Tour')], default='CONVENTIONAL', help_text='Tour type: Conventional Tour or Muslim Tour (for Indonesian citizens).', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['tour_type', 'is_active'], name='travel_tour_tour_ty_2925a0_idx'),
        ),
    ]
