# Generated by Django 5.2.8 on 2026-01-08 17:29

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='tourpackage',
            name='commission_valid',
        ),
        migrations.RemoveIndex(
            model_name='tourpackage',
            name='travel_tour_categor_8f18b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='tourpackage',
            name='travel_tour_is_feat_762625_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='commission_notes',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='group_type',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='meeting_point',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='summary',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.IntegerField(default=0, help_text='Total booking amount in IDR (Indonesian Rupiah). Must be greater than zero.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tourdate',
            name='airline',
            field=models.CharField(blank=True, help_text='Airline for this tour date.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tipping_price',
            field=models.IntegerField(default=0, help_text='Tipping price in IDR (Indonesian Rupiah). Actual price can vary per date.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='visa_price',
            field=models.IntegerField(default=0, help_text='Visa price in IDR (Indonesian Rupiah). Actual price can vary per date.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='platform_fee',
            field=models.IntegerField(default=50000, help_text='Platform fee in IDR (default: Rp. 50,000).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0, help_text='Payment amount in IDR (Indonesian Rupiah). Must be greater than zero.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='seatslot',
            name='seat_number',
            field=models.CharField(db_index=True, help_text="Seat identifier (e.g., 'A1', 'B12', or sequential number).", max_length=20),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='price',
            field=models.IntegerField(default=0, help_text='Price per person in IDR (Indonesian Rupiah) for this tour date. Must be greater than zero.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='base_price',
            field=models.IntegerField(default=0, help_text='Reference price in IDR (Indonesian Rupiah). Actual price can vary per date.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='commission',
            field=models.IntegerField(default=0, help_text='Commission amount for the tour package.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking'], name='travel_paym_booking_200cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reviewed_by'], name='travel_paym_reviewe_6ed600_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transfer_date'], name='travel_paym_transfe_d5b155_idx'),
        ),
        migrations.AddIndex(
            model_name='seatslot',
            index=models.Index(fields=['tour_date', 'booking'], name='travel_seat_tour_da_984fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='tourdate',
            index=models.Index(fields=['departure_date'], name='travel_tour_departu_b9e232_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['slug'], name='travel_tour_slug_f6819e_idx'),
        ),
        migrations.AddIndex(
            model_name='tourpackage',
            index=models.Index(fields=['country'], name='travel_tour_country_4c974b_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='seatslot',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number', ''), _negated=True), name='seat_number_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='tourdate',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 1)), name='tour_date_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='tourdate',
            constraint=models.CheckConstraint(condition=models.Q(('total_seats__gte', 1)), name='tour_date_seats_positive'),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.CheckConstraint(condition=models.Q(('commission__isnull', True), ('commission__gte', 0), _connector='OR'), name='commission_valid'),
        ),
    ]
