# Generated by Django 5.2.8 on 2026-01-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_resellercommission_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tourdate',
            name='has_shopping_stop',
            field=models.BooleanField(default=False, help_text='Whether this tour date includes shopping stop. Allows multiple prices for the same departure date.'),
        ),
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together={('package', 'departure_date', 'has_shopping_stop')},
        ),
    ]
