# Generated by Django 5.2.8 on 2026-01-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_account_cus_email_4c4c85_idx_and_more'),
        ('travel', '0002_alter_booking_options_alter_itineraryitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tourpackage',
            name='fixed_commission_valid_when_fixed_type',
        ),
        migrations.RemoveIndex(
            model_name='tourpackage',
            name='travel_tour_city_4959e8_idx',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='commission_type',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='fixed_commission_amount',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='tags',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='commission',
            field=models.PositiveIntegerField(blank=True, help_text='Commission amount for the tour package.', null=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='description',
            field=models.TextField(help_text='Detailed description of the tour package.'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='summary',
            field=models.TextField(help_text='Summary of the tour package.'),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.CheckConstraint(condition=models.Q(('commission__isnull', True), ('commission__gte', 1), _connector='OR'), name='commission_valid'),
        ),
    ]
