# Generated by Django 5.2.8 on 2026-01-08 17:31

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_tourpackage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='tourdate',
            name='tour_date_price_positive',
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.IntegerField(default=0, help_text='Total booking amount in IDR (Indonesian Rupiah).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0, help_text='Payment amount in IDR (Indonesian Rupiah).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='price',
            field=models.IntegerField(default=0, help_text='Price per person in IDR (Indonesian Rupiah) for this tour date.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tourdate',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='tour_date_price_non_negative'),
        ),
    ]
