# Generated by Django 5.2.8 on 2025-12-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_tourpackage_tour_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='itinerary_pdf',
            field=models.FileField(blank=True, help_text='PDF file containing the detailed itinerary for the tour package.', null=True, upload_to='tours/itineraries/'),
        ),
    ]
