# Generated by Django 5.2.8 on 2025-12-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_tourpackage_itinerary_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='review_count',
        ),
        migrations.DeleteModel(
            name='TourReview',
        ),
    ]
