# Generated by Django 5.2.8 on 2026-01-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_tourdate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_flexible',
            field=models.BooleanField(default=False, help_text='If True, allows booking for any date without pre-created TourDate. TourDate will be created automatically on booking.'),
        ),
    ]
