# Generated by Django 5.2.8 on 2026-01-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('travel', '0003_remove_payment_payment_amount_positive_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tourpackage',
            name='commission_valid',
        ),
        migrations.RemoveIndex(
            model_name='seatslot',
            name='travel_seat_passeng_e4ab98_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatslot',
            name='travel_seat_passpor_f55464_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sender_account_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sender_account_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sender_bank_name',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='passenger_date_of_birth',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='passenger_email',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='passenger_gender',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='passenger_nationality',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='passenger_phone',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='passport_expiry_date',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='passport_issue_country',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='passport_issue_date',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='visa_expiry_date',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='visa_issue_date',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='visa_number',
        ),
        migrations.RemoveField(
            model_name='seatslot',
            name='visa_type',
        ),
        migrations.AddField(
            model_name='seatslot',
            name='passport',
            field=models.ImageField(blank=True, help_text='Passport image.', null=True, upload_to='passports/'),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.CheckConstraint(condition=models.Q(('commission__gte', 0)), name='commission_valid'),
        ),
    ]
