# Generated by Django 5.2.8 on 2026-01-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_tourpackage_fixed_commission_valid_when_fixed_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='group_type',
            field=models.CharField(choices=[('SMALL_GROUP', 'Small Group'), ('PRIVATE', 'Private'), ('LARGE_GROUP', 'Large Group'), ('FAMILY', 'Family'), ('COUPLE', 'Couple'), ('SOLO', 'Solo')], default='SMALL_GROUP', help_text='Type of group for this tour package.', max_length=20),
        ),
    ]
