# Generated by Django 5.2.8 on 2026-01-16 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_tourpackage_is_flexible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellercommission',
            name='amount',
            field=models.PositiveIntegerField(help_text='Total commission amount in IDR. For Level 0: (commission_per_seat × number_of_seats) - 100,000 IDR upline deduction. For Levels 1-3: fixed amount from deduction (Level 1: 50k, Level 2-3: 25k). Must be at least 1 IDR.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
