# Generated by Django 5.2.8 on 2026-01-09 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('travel', '0004_remove_tourpackage_commission_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Withdrawal amount in IDR (Indonesian Rupiah). Must be at least 1 IDR.', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current status of the withdrawal request.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from reseller or admin.')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes (e.g., reason for rejection, payment confirmation).')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the withdrawal was approved/rejected.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the withdrawal payment was completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin user who approved/rejected this withdrawal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('reseller', models.ForeignKey(help_text='Reseller requesting the withdrawal.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='account.resellerprofile')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reseller', 'status'], name='travel_with_reselle_18d938_idx'), models.Index(fields=['status', 'created_at'], name='travel_with_status_5ab75a_idx'), models.Index(fields=['created_at'], name='travel_with_created_1af16e_idx')],
            },
        ),
    ]
