# Generated by Django 5.2.8 on 2026-01-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_role_customerprofile'),
        ('travel', '0005_alter_resellercommission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer who created this booking (null if booked by reseller).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.customerprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reseller',
            field=models.ForeignKey(blank=True, help_text='Reseller who created this booking (null if booked by customer).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='account.resellerprofile'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', 'status'], name='travel_book_custome_2f1b8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', True), ('reseller__isnull', False)), models.Q(('customer__isnull', False), ('reseller__isnull', True)), _connector='OR'), name='booking_either_reseller_or_customer'),
        ),
    ]
