# Generated by Django 5.2.8 on 2026-01-20 02:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_booking_customer_alter_booking_reseller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="ISO 4217 currency code (e.g., 'USD', 'IDR', 'EUR').", max_length=3, unique=True)),
                ('name', models.CharField(help_text="Currency name (e.g., 'United States Dollar').", max_length=100)),
                ('symbol', models.CharField(help_text="Currency symbol (e.g., '$', '₨', '€').", max_length=10)),
                ('exchange_rate_to_idr', models.DecimalField(decimal_places=4, default=1.0, help_text='Exchange rate relative to IDR (1 unit of this currency = X IDR).', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='travel_curr_code_85196c_idx'), models.Index(fields=['is_active'], name='travel_curr_is_acti_38898a_idx')],
            },
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency used for pricing. If null, IDR is assumed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_packages', to='travel.currency'),
        ),
    ]
