# Generated by Django 5.2.8 on 2026-01-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_currency_tourpackage_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_rate_to_idr',
        ),
    ]
