# Generated by Django 5.2.8 on 2026-01-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_remove_currency_exchange_rate_to_idr'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tourdate',
            name='departure_city',
            field=models.CharField(blank=True, default='', help_text='City where the tour departs from (e.g., Jakarta, Medan, Surabaya).', max_length=100),
        ),
        migrations.AddField(
            model_name='tourdate',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes or additional information for this tour date.'),
        ),
        migrations.AlterUniqueTogether(
            name='tourdate',
            unique_together={('package', 'departure_date', 'has_shopping_stop', 'departure_city')},
        ),
    ]
