# Generated by Django 5.2.8 on 2026-01-26 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_tourdate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resellercommission',
            name='amount',
            field=models.PositiveIntegerField(help_text='Total commission amount in IDR. For Level 0: (commission_per_seat × seats) - (deduction_per_seat × seats). For Levels 1-3: percentage of total deduction (Level 1: 50%, Level 2-3: 25%). Must be at least 1 IDR.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
