# Generated by Django 5.2.8 on 2026-02-01 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_resellercommission_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tourdate',
            name='tour_date_seats_positive',
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='total_seats',
            field=models.PositiveIntegerField(help_text='Total number of seats available. Can be 0 for manually booked tours.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='tourdate',
            constraint=models.CheckConstraint(condition=models.Q(('total_seats__gte', 0)), name='tour_date_seats_non_negative'),
        ),
    ]
