# Generated by Django 5.2.8 on 2026-02-13 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_remove_tourdate_tour_date_seats_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Promo code used for this booking (if any).', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_discount_amount',
            field=models.IntegerField(default=0, help_text='Discount amount from promo in IDR.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Promo code (e.g. WELCOME10). Case-insensitive lookup.', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Short description shown to users.', max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], help_text='Percentage or fixed amount discount.', max_length=20)),
                ('discount_value', models.PositiveIntegerField(help_text='For PERCENTAGE: 1-100. For FIXED_AMOUNT: amount in IDR.')),
                ('min_purchase_amount', models.PositiveIntegerField(default=0, help_text='Minimum purchase amount in IDR to use this promo.')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Max total uses across all users. Null = unlimited.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this promo has been used.')),
                ('valid_from', models.DateTimeField(help_text='Start of validity period.')),
                ('valid_until', models.DateTimeField(help_text='End of validity period.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this promo is active.')),
                ('applicable_to', models.CharField(choices=[('TOUR', 'Tour Booking'), ('ITINERARY', 'Itinerary Purchase'), ('BOTH', 'Both Tour and Itinerary')], default='BOTH', help_text='Where this promo can be applied.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='travel_prom_code_a8547d_idx'), models.Index(fields=['is_active'], name='travel_prom_is_acti_a5a095_idx'), models.Index(fields=['valid_from', 'valid_until'], name='travel_prom_valid_f_b25a87_idx')],
            },
        ),
    ]
