# Generated by Django 5.2.8 on 2026-02-14 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_booking_promo_code_booking_promo_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can use this promo (only if is_user_specific=True).', related_name='allowed_promo_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_user_specific',
            field=models.BooleanField(default=False, help_text='If True, only specified users can use this promo.'),
        ),
    ]
