# Generated by Django 5.2.8 on 2026-02-26 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_promocode_allowed_users_promocode_is_user_specific'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='customers_only',
            field=models.BooleanField(default=False, help_text='If True, resellers cannot use this promo. Only customers are allowed.'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='Max uses per individual user. Null = unlimited. Set to 1 for one-time-per-customer.', null=True),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, help_text='When the promo code was used.')),
                ('promo_code', models.ForeignKey(help_text='The promo code that was used.', on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='travel.promocode')),
                ('user', models.ForeignKey(help_text='The user who used the promo code.', on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['promo_code', 'user'], name='travel_prom_promo_c_c8d13d_idx'), models.Index(fields=['user'], name='travel_prom_user_id_b1081c_idx')],
            },
        ),
    ]
