# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0016_alter_tourdate_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourpackage",
            name="is_guaranteed",
            field=models.BooleanField(
                default=False,
                help_text="If True, the tour is confirmed to depart (Pasti Jalan) even if capacity is not yet filled.",
            ),
        ),
    ]
