# Generated by Django 5.2.8

from django.db import migrations, models

from travel.countries import canonicalize_country


def canonicalize_existing_countries(apps, schema_editor):
    TourPackage = apps.get_model("travel", "TourPackage")
    for tour in TourPackage.objects.all().only("id", "country"):
        canonical = canonicalize_country(tour.country)
        if canonical != tour.country:
            TourPackage.objects.filter(pk=tour.id).update(country=canonical)


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0017_tourpackage_is_guaranteed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourpackage",
            name="country",
            field=models.CharField(
                help_text=(
                    "Country where the tour takes place (e.g., 'China', 'Japan'). "
                    "Use the country, not a city or region, so filters match."
                ),
                max_length=255,
            ),
        ),
        migrations.RunPython(
            canonicalize_existing_countries,
            migrations.RunPython.noop,
        ),
    ]
