# Generated by Django 5.2.8 on 2026-01-11 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Board title (e.g., '5D4N China Tour - Jan 2024')", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('is_public', models.BooleanField(default=True, help_text='If True, board is publicly accessible via shareable link')),
                ('share_token', models.CharField(db_index=True, help_text='Unique token for sharing (auto-generated)', max_length=64, unique=True)),
                ('allow_editing', models.BooleanField(default=False, help_text='Allow public editing (or read-only for public, edit for owners)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itinerary_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Itinerary Board',
                'verbose_name_plural': 'Itinerary Boards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, help_text='Activity start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Activity end time', null=True)),
                ('date', models.DateField(blank=True, help_text='Specific date (if different from column context)', null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='itinerary/card_covers/')),
                ('color', models.CharField(blank=True, help_text='Card accent color (hex code)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Position within column')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Itinerary Card',
                'verbose_name_plural': 'Itinerary Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryCardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='itinerary/attachments/')),
                ('name', models.CharField(help_text='Display name for the attachment', max_length=255)),
                ('file_type', models.CharField(help_text='MIME type or file extension', max_length=50)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='itinerary.itinerarycard')),
            ],
            options={
                'verbose_name': 'Card Attachment',
                'verbose_name_plural': 'Card Attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryCardChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Checklist', max_length=255)),
                ('items', models.JSONField(default=list, help_text='List of {text: str, completed: bool, id: str} objects')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='itinerary.itinerarycard')),
            ],
            options={
                'verbose_name': 'Card Checklist',
                'verbose_name_plural': 'Card Checklists',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryCardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='itinerary.itinerarycard')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Comment',
                'verbose_name_plural': 'Card Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('color', models.CharField(default='#0079bf', help_text='Hex color code for column header', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='itinerary.itineraryboard')),
            ],
            options={
                'verbose_name': 'Itinerary Column',
                'verbose_name_plural': 'Itinerary Columns',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='itinerarycard',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='itinerary.itinerarycolumn'),
        ),
        migrations.AddIndex(
            model_name='itineraryboard',
            index=models.Index(fields=['share_token'], name='itinerary_i_share_t_0be405_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryboard',
            index=models.Index(fields=['slug'], name='itinerary_i_slug_974d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarycolumn',
            index=models.Index(fields=['board', 'order'], name='itinerary_i_board_i_711937_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarycard',
            index=models.Index(fields=['column', 'order'], name='itinerary_i_column__74963d_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarycard',
            index=models.Index(fields=['date', 'start_time'], name='itinerary_i_date_765799_idx'),
        ),
    ]
