# Generated by Django 5.2.8 on 2026-01-20 03:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_supplierprofile_bank_account_name_and_more'),
        ('travel', '0007_currency_tourpackage_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Board title (e.g., '5D4N China Tour - Jan 2024')", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('is_public', models.BooleanField(default=True, help_text='If True, board is publicly accessible via shareable link')),
                ('share_token', models.CharField(db_index=True, help_text='Unique token for sharing (auto-generated)', max_length=64, unique=True)),
                ('allow_editing', models.BooleanField(default=False, help_text='Allow public editing (or read-only for public, edit for owners)')),
                ('price', models.IntegerField(default=0, help_text='Price for accessing this itinerary board in IDR (Indonesian Rupiah).', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this itinerary board is active and available for purchase.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, help_text='Currency used for pricing. If null, IDR is assumed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_boards', to='travel.currency')),
                ('supplier', models.ForeignKey(help_text='Supplier who created and owns this itinerary board.', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_boards', to='account.supplierprofile')),
            ],
            options={
                'verbose_name': 'Itinerary Board',
                'verbose_name_plural': 'Itinerary Boards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, help_text='Activity start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Activity end time', null=True)),
                ('date', models.DateField(blank=True, help_text='Specific date (if different from column context)', null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='itinerary/card_covers/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position within column')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Itinerary Card',
                'verbose_name_plural': 'Itinerary Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryCardAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='itinerary/attachments/')),
                ('name', models.CharField(help_text='Display name for the attachment', max_length=255)),
                ('file_type', models.CharField(help_text='MIME type or file extension', max_length=50)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='itinerary.itinerarycard')),
            ],
            options={
                'verbose_name': 'Card Attachment',
                'verbose_name_plural': 'Card Attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryCardChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Checklist', max_length=255)),
                ('items', models.JSONField(default=list, help_text='List of {text: str, completed: bool, id: str} objects')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='itinerary.itinerarycard')),
            ],
            options={
                'verbose_name': 'Card Checklist',
                'verbose_name_plural': 'Card Checklists',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='itinerary.itineraryboard')),
            ],
            options={
                'verbose_name': 'Itinerary Column',
                'verbose_name_plural': 'Itinerary Columns',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='itinerarycard',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='itinerary.itinerarycolumn'),
        ),
        migrations.CreateModel(
            name='ItineraryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active - Customer can view'), ('EXPIRED', 'Expired - No longer accessible'), ('COMPLETED', 'Completed - Transaction finished'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current status of the transaction.', max_length=20)),
                ('amount', models.IntegerField(default=0, help_text='Amount paid for this transaction in IDR (snapshot from board price).', validators=[django.core.validators.MinValueValidator(0)])),
                ('access_duration_days', models.PositiveIntegerField(default=30, help_text='Number of days the customer has access to the itinerary.', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When the transaction was activated (customer got access).', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="When the customer's access expires.", null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the transaction was completed or cancelled.', null=True)),
                ('transaction_number', models.CharField(db_index=True, help_text='Unique transaction reference number (e.g., IT-2026-000001).', max_length=20, unique=True)),
                ('external_reference', models.CharField(blank=True, help_text='Optional external reference (e.g., payment gateway transaction ID).', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transaction.')),
                ('board', models.ForeignKey(help_text='The itinerary board being accessed.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='itinerary.itineraryboard')),
                ('booking', models.ForeignKey(blank=True, help_text='Related tour booking that triggered this itinerary access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_transactions', to='travel.booking')),
                ('customer', models.ForeignKey(help_text='Customer who has access to the itinerary.', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Itinerary Transaction',
                'verbose_name_plural': 'Itinerary Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='itineraryboard',
            index=models.Index(fields=['supplier', 'is_public'], name='itinerary_i_supplie_92c00b_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryboard',
            index=models.Index(fields=['supplier', 'is_active'], name='itinerary_i_supplie_f692e4_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryboard',
            index=models.Index(fields=['is_active', 'is_public'], name='itinerary_i_is_acti_a53c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryboard',
            index=models.Index(fields=['share_token'], name='itinerary_i_share_t_0be405_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryboard',
            index=models.Index(fields=['slug'], name='itinerary_i_slug_974d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryboard',
            index=models.Index(fields=['created_at'], name='itinerary_i_created_264e35_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarycolumn',
            index=models.Index(fields=['board', 'order'], name='itinerary_i_board_i_711937_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarycard',
            index=models.Index(fields=['column', 'order'], name='itinerary_i_column__74963d_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarycard',
            index=models.Index(fields=['date', 'start_time'], name='itinerary_i_date_765799_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarytransaction',
            index=models.Index(fields=['customer', 'status'], name='itinerary_i_custome_af6f92_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarytransaction',
            index=models.Index(fields=['board', 'customer'], name='itinerary_i_board_i_b1c17b_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarytransaction',
            index=models.Index(fields=['board', 'status'], name='itinerary_i_board_i_7babe5_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarytransaction',
            index=models.Index(fields=['booking'], name='itinerary_i_booking_8afd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarytransaction',
            index=models.Index(fields=['status', 'expires_at'], name='itinerary_i_status_c05ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarytransaction',
            index=models.Index(fields=['status', 'created_at'], name='itinerary_i_status_e9afae_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerarytransaction',
            index=models.Index(fields=['created_at'], name='itinerary_i_created_86062c_idx'),
        ),
    ]
