# Generated by Django 5.2.8 on 2026-01-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryboard',
            name='allow_editing',
        ),
    ]
