# Generated by Django 5.2.8 on 2026-01-24 04:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_remove_itineraryboard_allow_editing'),
        ('travel', '0009_alter_tourdate_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarytransaction',
            name='payment_amount',
            field=models.IntegerField(blank=True, help_text='Payment amount uploaded by customer/reseller in IDR.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='itinerarytransaction',
            name='payment_proof_image',
            field=models.ImageField(blank=True, help_text='Upload of the bank transfer slip or screenshot.', null=True, upload_to='itinerary_payments/proof/'),
        ),
        migrations.AddField(
            model_name='itinerarytransaction',
            name='payment_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the payment was reviewed.', null=True),
        ),
        migrations.AddField(
            model_name='itinerarytransaction',
            name='payment_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_payments_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itinerarytransaction',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, help_text='Status of the payment (null if no payment uploaded yet).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itinerarytransaction',
            name='payment_transfer_date',
            field=models.DateField(blank=True, help_text='Date when the transfer was made. Cannot be in the future.', null=True),
        ),
        migrations.AddIndex(
            model_name='itinerarytransaction',
            index=models.Index(fields=['payment_status'], name='itinerary_i_payment_449400_idx'),
        ),
    ]
