# Generated by Django 5.2.8 on 2026-01-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_delete_itinerarycardcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarycard',
            name='color',
        ),
        migrations.RemoveField(
            model_name='itinerarycolumn',
            name='color',
        ),
    ]
