# Generated by Django 5.2.8 on 2026-01-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_itinerarytransaction_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryboard',
            name='package_image',
            field=models.ImageField(blank=True, help_text='Package image to be displayed on itinerary detail page.', null=True, upload_to='itinerary_boards/packages/'),
        ),
        migrations.AddField(
            model_name='itineraryboard',
            name='video_link',
            field=models.URLField(blank=True, help_text='Link to YouTube or Instagram video/short to be shown on frontend.', max_length=500),
        ),
    ]
