# Generated by Django 5.2.8 on 2026-01-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_itineraryboard_package_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarytransaction',
            name='access_duration_days',
        ),
        migrations.AddField(
            model_name='itinerarytransaction',
            name='arrival_date',
            field=models.DateField(blank=True, help_text='Arrival/return date of the trip. Access expires 2 days after this date.', null=True),
        ),
        migrations.AddField(
            model_name='itinerarytransaction',
            name='departure_date',
            field=models.DateField(blank=True, help_text='Departure date of the trip. Access starts from this date.', null=True),
        ),
    ]
