# Generated by Django 5.2.8 on 2026-02-13 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_remove_itinerarytransaction_access_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarytransaction',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Promo code used for this transaction (if any).', max_length=50),
        ),
        migrations.AddField(
            model_name='itinerarytransaction',
            name='promo_discount_amount',
            field=models.IntegerField(default=0, help_text='Discount amount from promo in IDR.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
