from django.urls import path

from .views import (
    AgentBoardColumnCreateView,
    AgentBoardDetailView,
    AgentBoardListCreateView,
    AgentBoardPackageImageView,
    AgentBoardPublishView,
    AgentCardCoverView,
    AgentCardCreateView,
    AgentCardDetailView,
    AgentCountryListView,
    AgentCurrencyListView,
    AgentSupplierLookupView,
    AgentTourDateCreateView,
    AgentTourDateDetailView,
    AgentTourDetailView,
    AgentTourImageCreateView,
    AgentTourImageDetailView,
    AgentTourItineraryPdfView,
    AgentTourListCreateView,
    AgentTourPublishView,
    AgentTourUnpublishView,
)

urlpatterns = [
    path("suppliers/", AgentSupplierLookupView.as_view(), name="agent-suppliers"),
    path("currencies/", AgentCurrencyListView.as_view(), name="agent-currencies"),
    path("countries/", AgentCountryListView.as_view(), name="agent-countries"),
    path("tours/", AgentTourListCreateView.as_view(), name="agent-tours"),
    path("tours/<int:pk>/", AgentTourDetailView.as_view(), name="agent-tour-detail"),
    path("tours/<int:pk>/images/", AgentTourImageCreateView.as_view(), name="agent-tour-images"),
    path(
        "tours/<int:pk>/images/<int:image_id>/",
        AgentTourImageDetailView.as_view(),
        name="agent-tour-image-detail",
    ),
    path(
        "tours/<int:pk>/itinerary-pdf/",
        AgentTourItineraryPdfView.as_view(),
        name="agent-tour-itinerary-pdf",
    ),
    path("tours/<int:pk>/dates/", AgentTourDateCreateView.as_view(), name="agent-tour-dates"),
    path(
        "tours/<int:pk>/dates/<int:date_id>/",
        AgentTourDateDetailView.as_view(),
        name="agent-tour-date-detail",
    ),
    path("tours/<int:pk>/publish/", AgentTourPublishView.as_view(), name="agent-tour-publish"),
    path("tours/<int:pk>/unpublish/", AgentTourUnpublishView.as_view(), name="agent-tour-unpublish"),
    path("boards/", AgentBoardListCreateView.as_view(), name="agent-boards"),
    path("boards/<int:pk>/", AgentBoardDetailView.as_view(), name="agent-board-detail"),
    path(
        "boards/<int:pk>/package-image/",
        AgentBoardPackageImageView.as_view(),
        name="agent-board-package-image",
    ),
    path(
        "boards/<int:pk>/columns/",
        AgentBoardColumnCreateView.as_view(),
        name="agent-board-columns",
    ),
    path("boards/<int:pk>/publish/", AgentBoardPublishView.as_view(), name="agent-board-publish"),
    path("columns/<int:pk>/cards/", AgentCardCreateView.as_view(), name="agent-column-cards"),
    path("cards/<int:pk>/", AgentCardDetailView.as_view(), name="agent-card-detail"),
    path("cards/<int:pk>/cover/", AgentCardCoverView.as_view(), name="agent-card-cover"),
]
